spring:
  profiles:
    active: dev8001

---
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

spring:
  profiles: dev8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud-db1?serverTimezone=UTC
    username: root
    password: huangjian1
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: eureka-provider-dept
  main:
    allow-bean-definition-overriding: true


server:
  port: 8001

eureka:
  instance:
    instance-id: springcloud-provider-dept8001
    prefer-ip-address: true #可以在eureka显示服务ip
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true


---
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

spring:
  profiles: dev8002
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud-db2?serverTimezone=UTC
    username: root
    password: huangjian1
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: eureka-provider-dept
  main:
    allow-bean-definition-overriding: true


server:
  port: 8002
eureka:
  instance:
    instance-id: springcloud-provider-dept8002
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true
