spring:
  profiles:
    active: dev7003

---
server:
  port: 7003

spring:
  profiles: dev7003

eureka:
  instance:
    hostname: eureka7003.com
  client:
    register-with-eureka: true #时候向eureka注册自己
    fetch-registry: false #false表示自己为注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

info:
  app.name: ray-7003
  comany.name: ray

---
server:
  port: 7002

spring:
  profiles: dev7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: true #时候向eureka注册自己
    fetch-registry: false #false表示自己为注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/

info:
  app.name: ray-7002
  comany.name: ray
---
server:
  port: 7001

spring:
  profiles: dev7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: true #时候向eureka注册自己
    fetch-registry: false #false表示自己为注册中心
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

info:
  app.name: ray-7001
  comany.name: ray